### ISSUE TITLE
json requirement

### ISSUE THREAD

**Issue by janscience** [relacs/relacsed_nix#3]
Running
```
python3 setup.py install 
```
throws
```
No local packages or working download links found for json
error: Could not find suitable distribution for Requirement.parse('json')
```
There is indeed no pip package nor an apt python3-json package. But nevertheless I can import `json`. `json` is already included in the standard python library. So probably you can simply remove `json` from the `install_req` list in `setup.py`.

**Comment by janscience** [comment]
I get the same error when installing nixio.

**Comment by jgrewe** [comment]
that is surprising, nixio uses json but there is no dependency on it

**Comment by jgrewe** [comment]
done
