### ISSUE TITLE
nixio requirement

### ISSUE THREAD

**Issue by janscience** [relacs/relacsed_nix#4]
nixio needs to have version >= 1.5 ?

With nixio 1.4.9 I got

```
  File "/usr/local/lib/python3.8/dist-packages/rlxnix-0.5-py3.8.egg/rlxnix/stimulus.py", line 14, in Stimulus
    def __init__(self, stimulus_multi_tag: nixio.MultiTag, index: int, traces, 
AttributeError: module 'nixio' has no attribute 'MultiTag'
```

**Comment by jgrewe** [comment]
done

**Comment by jpresern** [comment]
you guys are busy on nixing relacs … :)

how are you/

**Comment by jgrewe** [comment]
Hey @jpresern all good here ;) Actually, we are quite far with that, there are only rare occasions I consult the old-style stimuli.dat file for cross-checking. Now this is an attempt to reduce the effort for accessing the data.

Best!
